### ISSUE TITLE
InvalidArgumentException: SSL CA bundle not found

### ISSUE THREAD

**Issue by devpikachu** [nextcloud/integration_google#132]
Getting an SSL CA bundle not found exception when trying to import from Drive. Importing from Photos seems to be working fine.

Logs:
```
Google Drive import error: Unknown job failure. InvalidArgumentException: SSL CA bundle not found: /tmp/oc_tmp_u3m3oO-.crt in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php:363 Stack trace: #0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(59): GuzzleHttp\Handler\CurlFactory->applyHandlerOptions() #1 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory->create() #2 /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php(146): GuzzleHttp\Handler\CurlHandler->__invoke() #3 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}() #4 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #5 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #6 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #7 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #9 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #10 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #11 /var/www/nextcloud/lib/private/Http/Client/Client.php(218): GuzzleHttp\Client->request() #12 /var/www/nextcloud/apps/integration_google/lib/Service/GoogleAPIService.php(139): OC\Http\Client\Client->get() #13 /var/www/nextcloud/apps/integration_google/lib/Service/GoogleDriveAPIService.php(267): OCA\Google\Service\GoogleAPIService->request() #14 /var/www/nextcloud/apps/integration_google/lib/Service/GoogleDriveAPIService.php(199): OCA\Google\Service\GoogleDriveAPIService->importFiles() #15 /var/www/nextcloud/apps/integration_google/lib/BackgroundJob/ImportDriveJob.php(38): OCA\Google\Service\GoogleDriveAPIService->importDriveJob() #16 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\Google\BackgroundJob\ImportDriveJob->run() #17 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(58): OCP\BackgroundJob\Job->start() #18 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(48): OCP\BackgroundJob\QueuedJob->start() #19 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\QueuedJob->execute() #20 {main}
```

**Comment by tcitworld** [comment]
@devpikachu Do you still have this issue? Do you have the `files_external` app activated?

**Comment by devpikachu** [comment]
@tcitworld I'm unfortunately unable to answer that question, as the Nextcloud server in question has been decommissioned in the meantime.
