### ISSUE TITLE
Migration breaks moving .htaccess file

### ISSUE THREAD

**Issue by lordratner** [nextcloud/integration_google#164]
### Which version of integration_google are you using?

2.1.0

### Which version of Nextcloud are you using?

28.0.1 RC1

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox and Chrome

### Describe the Bug

Migration dies when it encounters an .htaccess file from an archived website

```
[integration_google] Error: Google Drive import error: Unknown job failure. OCP\Files\ForbiddenException: Invalid path: files/Google Drive Import/Projects/Transfer/www/driver/html/.htaccess in /var/www/html/lib/private/Files/Storage/Local.php:510
Stack trace:
#0 /var/www/html/lib/private/Files/Storage/Local.php(288): OC\Files\Storage\Local->getSourcePath('files/Google Dr...')
#1 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(224): OC\Files\Storage\Local->file_exists('files/Google Dr...')
#2 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(224): OC\Files\Storage\Wrapper\Wrapper->file_exists('files/Google Dr...')
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(224): OC\Files\Storage\Wrapper\Wrapper->file_exists('files/Google Dr...')
#4 /var/www/html/lib/private/Files/View.php(1330): OC\Files\Storage\Wrapper\Wrapper->file_exists('files/Google Dr...')
#5 /var/www/html/lib/private/Files/View.php(1374): OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), 'files/Google Dr...', '/5d7b0bbd-6ac5-...')
#6 /var/www/html/lib/private/Files/Node/Root.php(203): OC\Files\View->getFileInfo('/5d7b0bbd-6ac5-...', false)
#7 /var/www/html/lib/private/Files/Node/Folder.php(135): OC\Files\Node\Root->get('/5d7b0bbd-6ac5-...')
#8 /var/www/html/lib/private/Files/Node/Folder.php(144): OC\Files\Node\Folder->get('.htaccess')
#9 /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php(330): OC\Files\Node\Folder->nodeExists('.htaccess')
#10 /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php(180): OCA\Google\Service\GoogleDriveAPIService->importFiles('5d7b0bbd-6ac5-3...', '/Google Drive I...', 500000000, 0, 0, Array)
#11 /var/www/html/custom_apps/integration_google/lib/BackgroundJob/ImportDriveJob.php(36): OCA\Google\Service\GoogleDriveAPIService->importDriveJob('5d7b0bbd-6ac5-3...')
#12 /var/www/html/lib/public/BackgroundJob/Job.php(81): OCA\Google\BackgroundJob\ImportDriveJob->run(Array)
#13 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(57): OCP\BackgroundJob\Job->start(Object(OC\BackgroundJob\JobList))
#14 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\QueuedJob->start(Object(OC\BackgroundJob\JobList))
#15 /var/www/html/cron.php(152): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#16 {main}
	from ? by 5d7b0bbd-6ac5-3780-a194-bb396ed5c6f9 at Dec 18, 2023, 9:43:56 PM

```

### Expected Behavior

Either transfer the file or skip it. 

Once I deleted the files from google (they had to be permanently deleted, not just in the trash), it worked. 

### To Reproduce

Try to migrate a drive with .htaccess files.

**Comment by marcelklehr** [comment]
Thank you for reporting this!
